### ISSUE TITLE
[tracker] what needs to be translated

### ISSUE THREAD

**Issue by ArchFeh** [ruyisdk/ruyisdk-website#1]
# Japanese
conten/ja:
目录下的所有_index.md文件以及https://github.com/ruyisdk/ruyisdk-website/blob/main/content/ja/blog/news/announce.md
# Korean
content/ko:conten/ja:
目录下的所有_index.md文件以及https://github.com/ruyisdk/ruyisdk-website/blob/main/content/ko/blog/news/announce.md
@alapha23

**Comment by alapha23** [comment]
#2
