### ISSUE TITLE
i18n: 德语翻译

### ISSUE THREAD

**Issue by ArchFeh** [ruyisdk/ruyisdk-website#6]
需要翻译的文件有：

- [x] https://github.com/ruyisdk/ruyisdk-website/blob/05ba6712a93f62e8ba882c422a759e8d7f042389/content/de/about/index.md
- [x] https://github.com/ruyisdk/ruyisdk-website/blob/05ba6712a93f62e8ba882c422a759e8d7f042389/content/de/blog/news/announce.md
- [x] https://github.com/ruyisdk/ruyisdk-website/blob/05ba6712a93f62e8ba882c422a759e8d7f042389/content/de/community/_index.md
- [x] https://github.com/ruyisdk/ruyisdk-website/blob/05ba6712a93f62e8ba882c422a759e8d7f042389/content/de/download/_index.md
- [x] https://github.com/ruyisdk/ruyisdk-website/blob/05ba6712a93f62e8ba882c422a759e8d7f042389/content/de/supported/_index.md
- [x] https://github.com/ruyisdk/ruyisdk-website/blob/05ba6712a93f62e8ba882c422a759e8d7f042389/content/de/_index.md

**Comment by YunxiangLuo** [comment]
内容初步完成，见https://github.com/YunxiangLuo/ruyisdk-website/tree/main/content/de，校正后提交pr。

**Comment by ArchFeh** [comment]
感谢，已合并！
